[phases.install]
cmds = [
  "composer install --ignore-platform-reqs --no-scripts"
]

[phases.start]
cmds = [
  "php bin/console doctrine:migrations:migrate --env=prod --no-interaction || true",
  "php -S 0.0.0.0:$PORT -t public"
]
